config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'restaurants#index'
  resources :dashboard, only: :index
  resources :dashboard_owner, only: :index
  resources :restaurants do
    resources :reservations do
      member do
        patch "approve"
        patch "decline"
      end
    end
  end
  resources :reservations, only: [] do
    resources :order_items, only: [:create, :index]
  end

  get 'search', to: 'search#index'
  get 'dashboard_owner/index'
  get 'dashboard/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :restaurant
  # has_many :order_items
end

app/models/menuitem.rb
class MenuItem < ApplicationRecord
  belongs_to :restaurant
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :reservation
  belongs_to :menu_item
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :reservation
  belongs_to :menu_item
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :order_items, dependent: :destroy
  def cart
    sum = 0
    self.order_items.each do |item|
      sum +=  item.menu_item.price
    end

    return sum
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_many :reservations, dependent: :destroy
  has_many :menu_items, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true



  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

   include PgSearch
   pg_search_scope :search_by_category_name_address,
    against: [ :category, :name, :address ],
    using: {
      tsearch: { prefix: true }
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
  { host: ENV["welunch10.herokuapp.com"] || "localhost:3000" }
end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @my_reservations = current_user.reservations

  end


end

app/controllers/dashboard_owner_controller.rb
class DashboardOwnerController < ApplicationController
  def index
    @the_reservations = current_user.reservations
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_reservation, only: [:create, :show, :index]
# t.bigint "reservation_id"
# t.bigint "menu_item_id"

  def create
    # create an order item using the menu_item_id from the params
    @order_item = OrderItem.new(order_item_params)
    # and the reservation_id from the url!
    @order_item.reservation = @reservation
    if @order_item.save
    # redirect_to restaurant_reservation_path(@reservation.restaurant, @reservation)
    # redirect to the reservation show page!

      respond_to do |format|
          format.html { redirect_to restaurant_reservation_path(@reservation.restaurant, @reservation) }
          format.js
      end
    end
  end

  def index
    @items = @reservation.order_items

  end

  private

  def order_item_params
    params.require(:order_item).permit(:menu_item_id)
  end
  def set_reservation
    @reservation = Reservation.find(params[:reservation_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reservations_controller.rb
#Question to teacher: where to display? Dashboard?


class ReservationsController < ApplicationController
  before_action :set_restaurant, only: [:new,:update, :show, :create, :edit, :approve, :decline]
  before_action :set_reservation, only: [:edit, :update, :show, :destroy, :approve, :decline]


  def index
    @reservation = Reservation.all
  end

  def new
    #i need to grab my restaurant_id in my url
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.restaurant = @restaurant
    @reservation.user = current_user
    if @reservation.save
      flash[:notice] = "Succesfully made a reservation"
      redirect_to restaurant_reservation_path(@restaurant, @reservation)
    else
      flash[:alert] = "Reservation unsuccessfull, please try again"
      render :new
    end
  end

  def edit
    @reservation.user = current_user
  end

  def update
    @reservation.update(reservation_params)
    redirect_to dashboard_index_path

  end

  def show
    @order_item = OrderItem.new
  end

  def destroy

    @reservation.destroy
    redirect_to dashboard_index_path

  end

  def approve
    @reservation.status = "approved"
    @reservation.save
    redirect_to dashboard_owner_index_path
  end

  def decline
    @reservation.status = "Declined"
    @reservation.save
    redirect_to dashboard_owner_index_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:time, :number_of_people)
    #why only permit time? Is it not mandatory?
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    # @restaurants = Restaurant.all
    if params[:query]
      @restaurants = Restaurant.search_by_category_name_address(params[:query])
      @search_term = params[:query]
    else
      @restaurants = Restaurant.all
    end
    @restaurants = @restaurants.where.not(latitude: nil, longitude: nil)
    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: { content: render_to_string(partial: "/restaurants/map_box", locals: { restaurant: restaurant }) }
      }

  end
end

def show
  @restaurant = Restaurant.find(params[:id])
  @reservation = Reservation.new

end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    if params[:query]
      @restaurants = Restaurant.search_by_category_name_address(params[:query])
      @search_term = params[:query]
    else
      @restaurants = Restaurant.all
    end
    @restaurants = @restaurants.where.not(latitude: nil, longitude: nil)
    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude
      }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/dashboard/index.html.erb
<div class="menu-dashboard">
  <div class="container">
    <div class="row">
      <% @my_reservations.each do |reservation| %>
      <div class="col-md-12" >
        <div class="message">
          <div> <%= image_tag reservation.restaurant.picture, width: "200px", height: "100px", crop: :fill%></div>

          <div class="message-name"> <p><%= reservation.time.to_formatted_s(:long) %></p>
            <% if reservation.status == "approved" %>
            <h6 class="approved"><%= reservation.status %></h6>
            <% elsif reservation.status == "declined" %>
            <h6 class="declined"><%= reservation.status %></h6>
            <% elsif %>
            <% reservation.status == "pending" %>
                <h6 class="pending"><%= reservation.status %></h6>

              <% end %>
          </div>
          <div class="message-body">
            <h3><%= reservation.restaurant.name %></h3>
            <p><%= reservation.restaurant.address %></p>
            <p>Table for <%= reservation.number_of_people %></p>
          </div>
          <div class="message-status">
            <%= link_to reservation_order_items_path(reservation) do %>
            <div class="status pending"><%= link_to "edit", edit_restaurant_reservation_path(reservation.restaurant, reservation), class: "btn btn-primary" %>
              <%= link_to "cancel", restaurant_reservation_path(reservation.restaurant, reservation), method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-primary" %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  </div>
</div>

app/views/dashboard_owner/index.html.erb
<h1>Owner</h1>


<div>
<% @the_reservations.each do |reservation| %>
<p><%= reservation.restaurant.name %></p>
  <p><%= reservation.time.to_formatted_s(:long) %></p>
  <p><%= reservation.number_of_people %></p>
<%= link_to "Approve", approve_restaurant_reservation_path(reservation.restaurant, reservation), method: :patch, class: "btn btn-primary" %>
<%= link_to "Decline", decline_restaurant_reservation_path(reservation.restaurant, reservation), method: :patch, class: "btn btn-danger" %>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">




  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <title>WeLunch</title>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag "application" %>

  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>
  <%= javascript_pack_tag "map" %>

  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>

  <%= javascript_pack_tag "map" %>
  <%= javascript_pack_tag "application" %>



  <%= yield(:after_js) %>

  </html>

app/views/order_items/_single_item.html.erb
<p class="border-bottom">
  <%= item.name %> - <%= item.price %>
</p>

app/views/order_items/create.js.erb
function addNewItem(item){
  let listOrder = document.getElementById('list-order');
  listOrder.insertAdjacentHTML('beforeend', item);
}

addNewItem('<%= j render "order_items/single_item", item: @order_item.menu_item %>');

app/views/order_items/index.html.erb
<div class="container">
  <div class="row">

      <div class="col-md-5">
        <h1>Your reservation:</h1>

        <div class="menu-container order-preview">
          <div class="menu">
            <div class="menu-body">
             <p class="reciept">Reservation: <%= @reservation.time.to_formatted_s(:long) %></p>
             <p class="reciept">People: <%= @reservation.number_of_people %></p>
            </div>
          </div>
          <% @items.each do |item| %>
            <div class="menu">
              <div class="menu-body">
                <h3><%= item.menu_item.name %></h3>
                <p><%= item.menu_item.description %></p>
              </div>
              <p>$<%= item.menu_item.price %></p>
            </div>
          <% end %>
        </div>

        <h2>Total Amount: $<%= @reservation.cart %></h2>
      </div>


    <div class="col-md-7">
      <%= image_tag "payment-form.png", class:"payment-form" %>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<h1> Bonjour!</h1>

app/views/reservations/_form.html.erb
<%= simple_form_for([@restaurant, @reservation]) do |r| %>
  <%= r.input :number_of_people %>
  <%= r.input :time %>
  <%= r.button :submit, class: "btn btn-primary"%>
<% end %>

app/views/reservations/edit.html.erb
<h1> Edit reservation </h1>

<%= render "form" %>

app/views/reservations/index.hmtl.erb
<h1>Reservations#index</h1>
<p>test test test</p>

app/views/reservations/new.html.erb
<%= render "form" %>

app/views/reservations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 card-white">
      <h2>Your order:</h2>
      <div id="list-order">
        <% @reservation.order_items.each do |order| %>
          <%= render "order_items/single_item", item: order.menu_item  %>
        <% end %>
      </div>

      <%= link_to "Confirm Order",reservation_order_items_path(@reservation), class: "btn btn-primary"%>
    </div>

    <div class="col-md-8">
      <div class="menu-container shopping-cart">
        <% @restaurant.menu_items.each do |menu_item| %>


        <div class="menu">

          <div class="menu-upvote">
            <i class="fa fa-cutlery" aria-hidden="true"></i>
            <div class="menu-count"></div>
          </div>

          <div class='menu-body'>
           <h3><%= menu_item.name %></h3>
           <p><%= menu_item.description %></p>
           <p><%= menu_item.price %></p>
         </div>

         <div>
           <%= simple_form_for([@reservation, @order_item], remote: true) do |f| %>
           <%= f.input :menu_item_id, as: :hidden, input_html: { value: menu_item.id } %>
           <%= f.submit value: "Add Item", class: "btn btn-primary" %>
           <% end %>
         </div>
       </div>
       <% end %>
     </div>

   </div>
 </div>
</div>


<!-- Modal -->
<!-- <div class="modal fade" id="shopping_cart" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4> Your current shopping cart</h4>

        <div class="modal-body">
          <% @reservation.order_items.each do |item| %>
          <p>
            <%= item.menu_item.name %> - <%= item.menu_item.price %>
          </p>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= link_to "Save changes",reservation_order_items_path(@reservation), class: "btn btn-primary"%>
        </div>
      </div>
    </div>
  </div>
</div>
 -->

app/views/restaurants/_map_box.html.erb
<p><%= link_to restaurant_path(restaurant) do %>
  <%= image_tag restaurant.picture, height: 200, width: 300, crop: :fill%>
<% end %></p>
<style>
  .dog-info {
    width: 100%;
    padding: 10px;
  }
</style>
<div class="map-box">
  <div class="res-info">
  <h4><%= restaurant.name %></h4>
  <p> <%= restaurant.address %></p>
  </div>
</div>

app/views/restaurants/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="4000">






  <!-- Wrapper for slides -->
  <div class="carousel-inner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), role="listbox">

    <div class="item carousel-item active" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner20.jpg" %>)">
   </div>


   <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner12.jpg" %>)">
   </div>

   <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner25.jpg" %>)">
   </div>

   <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner17.jpg" %>)">
   </div>

   <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner13.jpg" %>)">
   </div>



   <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner21.jpg" %>)">
   </div>

   <!-- <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner28.jpg" %>)">
   </div> -->
  <!--  <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner30.jpg" %>)">
   </div> -->

   <!-- <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner20.jpg" %>)">
   </div> -->
   <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner18.jpg" %>)">
   </div>

   <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner4.jpg" %>)">
   </div>
   <div class="item carousel-item" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_path "banner3.jpg" %>)">
   </div>



 </div>

 <div class="content-carousel">
  <div class="align-center">
    <div class="flex-item">
      <h1>WeLunch</h1>
      <p class="subtitle">Add time to your day</p>
      <div class="input-group search-style-home">

        <form action="/search" class="inline-form">

          <input type="text" class="form-control" name="query" placeholder="Search for city, category...">

          <span class="input-group-btn">

          </span>
</form>
</div>
<div>
</div>
</div>

</div>
</div>
</div>


<style>
  .feature-row {
    display: flex;
    justify-content: space-around;
    align-items: center;
    padding: 110px 100px;
  }
  .feature {
    text-align: center;
    width: 200px;
  }
</style>


  <div class="feature-row">
    <div class="feature">
      <i class="fa fa-fast-forward fa-3x"></i>
      <h3>
        1. Pre Order
      </h3>
    </div>
    <div class="feature">
      <i class="fa fa-clock-o fa-3x"></i>
      <h3>
        2. Set the time
      </h3>
    </div>
    <div class="feature">
      <i class="fa fa-cutlery fa-3x"></i>
      <h3>
        3. Eat on arrival
      </h3>
    </div>
  </div>

<div class="align-center">
  <a href="#restaurants-container">
    <i class="fa fa-chevron-circle-down" aria-hidden="true"></i>
  </a>
</div>
<div class="page-layout" id="restaurants-container">

  <div class="container">
    <div class="row">
      <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to restaurant_path(restaurant) do %>
        <div class="card style-border" style="background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(' <%= image_path restaurant.picture %>');">
          <h4><%= restaurant.name %></h4>
          <p class="card-category"><%#= restaurant.name %></p>
          <div class="card-description">
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  <div id="map" style="width: 100%; max-height: 86vh;" data-markers="<%= @markers.to_json %>">
  </div>
</div>


</div>








  <%= content_for(:after_js) do  %>
  <script>
    $('.carousel').carousel()
  </script>
  <% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 tall">

      <div class="sticky">
        <div class="restaurant-info">
          <h2><%= @restaurant.name %></h2>
          <p><%= @restaurant.address %></p>
        </div>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path @restaurant.picture %>);">
          <div class="card-category"><%= @restaurant.category %></div>
        </div>

        <div class="reservation-form">
          <%= render "reservations/form" %>
        </div>

      </div>

    </div>



    <div class="col-md-8">
      <div class="menu-container">

        <% @restaurant.menu_items.each do |item| %>

        <div class="menu">
          <div class='menu-upvote'>
            <i class="fa fa-cutlery" aria-hidden="true"></i>
            <div class='menu-count'></div>
          </div>

          <div class='menu-body'>
           <p><%= item.menu_category %></p>
           <h3><%= item.name %></h3>
           <p><%= item.description %></p>
         </div>

         <div class="price">$<%= item.price %></div>

            <!-- <ul class="list-inline menu-controls hidden-sm hidden-xs">
              <li><a href=""><i class="fa fa-heart"></i></a></li>
              <li><a href=""><i class="fa fa-share"></i></a></li>
              <li><a href=""><i class="fa fa-star"></i></a></li>
            </ul> -->
          </div>

          <% end %>

        </div>

      </div>
    </div>
  </div>

app/views/search/index.html.erb
<div class="page-layout">
  <div class="container">
    <div class="row">
      <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to restaurant_path(restaurant) do %>
        <div class="card style-border" style="background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(' <%= image_path restaurant.picture %>');">
          <h4><%= restaurant.name %></h4>
          <p class="card-category"><%#= restaurant.name %></p>
          <div class="card-description">
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  <div id="map" style="width: 100%; max-height: 100vh;" data-markers="<%= @markers.to_json %>">
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <!-- <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> by the I'm Still Standing Team
  </div> -->
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "Logo3.jpg", height: 300 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <!-- <#%= link_to "About", dashboard_index_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <#%= link_to "Map", dashboard_index_path, class: "navbar-wagon-item navbar-wagon-link" %> -->


      <%= link_to "Dashboard", dashboard_index_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "HM.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>